# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: geoglue
author: Global.health
logo: logo.png

# do not execute notebooks
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

repository:
  url: https://github.com/kraemer-lab/geoglue
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.autosummary

